/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author 52951
 */
public class MenuTetris extends javax.swing.JFrame {

    /**
     * Creates new form MenuTetris4
     */
    public MenuTetris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SALIR = new javax.swing.JLabel();
        AJUSTES = new javax.swing.JLabel();
        COMOJUGAR = new javax.swing.JLabel();
        JUGAR = new javax.swing.JLabel();
        PUNTAJE = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        SALIR.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        SALIR.setForeground(new java.awt.Color(255, 255, 255));
        SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonTetris.png"))); // NOI18N
        SALIR.setText("SALIR");
        SALIR.setDoubleBuffered(true);
        SALIR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(SALIR);
        SALIR.setBounds(100, 530, 200, 80);

        AJUSTES.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        AJUSTES.setForeground(new java.awt.Color(255, 255, 255));
        AJUSTES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonTetris.png"))); // NOI18N
        AJUSTES.setText("AJUSTES");
        AJUSTES.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AJUSTES);
        AJUSTES.setBounds(100, 420, 200, 80);

        COMOJUGAR.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        COMOJUGAR.setForeground(new java.awt.Color(255, 255, 255));
        COMOJUGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonTetris.png"))); // NOI18N
        COMOJUGAR.setText("COMO JUGAR");
        COMOJUGAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(COMOJUGAR);
        COMOJUGAR.setBounds(100, 320, 200, 80);

        JUGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botoncitoTetris.png"))); // NOI18N
        getContentPane().add(JUGAR);
        JUGAR.setBounds(100, 120, 200, 80);

        PUNTAJE.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        PUNTAJE.setForeground(new java.awt.Color(255, 255, 255));
        PUNTAJE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PUNTAJE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonTetris.png"))); // NOI18N
        PUNTAJE.setText("PUNTAJE");
        PUNTAJE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PUNTAJE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(PUNTAJE);
        PUNTAJE.setBounds(100, 220, 200, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tetrisImage.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 20, 247, 70);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.jpg"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 711);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTetris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTetris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AJUSTES;
    private javax.swing.JLabel COMOJUGAR;
    private javax.swing.JLabel JUGAR;
    private javax.swing.JLabel PUNTAJE;
    private javax.swing.JLabel SALIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
